blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Diskussionen
    url: https://github.com/michi-haensler/EcoTrack/discussions
    about: Nutze Diskussionen fÃ¼r Fragen und Ideen
  - name: ğŸ“– Dokumentation
    url: https://github.com/michi-haensler/EcoTrack/wiki
    about: Schau in die Wiki fÃ¼r Anleitungen und Dokumentation
